### ISSUE TITLE
Using the range slider disables all events in the page

### ISSUE THREAD

**Issue by vncscoelho** [xwpongithub/vue-range-slider#12]
I just realized that when I use this component all keypresses are somehow disabled.

**Comment by cosimochellini** [comment]
same

**Comment by jeff-silva** [comment]
Same here

**Comment by vncscoelho** [comment]
I don't know if this component is affiliated with https://nightcatsama.github.io/vue-slider-component. But it appears they are the same, but vue-slider-component doesnt't have the same issues and appears more finished.
