### ISSUE TITLE
How to add this in nuxt?

### ISSUE THREAD

**Issue by JenuelDev** [xwpongithub/vue-range-slider#27]
How to add this in nuxt?

**Comment by cryp2knight** [comment]
i was able to add it to nuxt, by creating a plugin like this


`// vue-range-slider.ts`
```ts
import Vue from "vue";
import 'vue-range-component/dist/vue-range-slider.css'

// @ts-ignore
import VueRangeSlider from "vue-range-component";

Vue.use(VueRangeSlider);
```

and then add the plugin on your nuxt config

`// nuxt.config.js`
```ts
plugins: [
    ...,
    { src: "~/plugins/vue-range-slider.ts", mode: "client" },
  ],
```

then you can use it on any component. Im using typescript but will still probably work on js

**Comment by JenuelDev** [comment]
thanks @cryp2knight , I actually was able to find the answer :) your answer also totally works :) thanks thanks
